# Generated by Django 6.0.6 on 2026-06-25 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curriculum', models.IntegerField(choices=[(0, 'Sin Plan'), (2017, 'Plan 2017'), (2023, 'Plan 2023'), (2024, 'Plan 2024')], default=2017)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField(blank=True, null=True, unique=True)),
                ('names', models.CharField(max_length=155)),
                ('father_surname', models.CharField(max_length=155)),
                ('mother_surname', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cui', 'names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=155)),
                ('father_surname', models.CharField(max_length=155)),
                ('mother_surname', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('laboratory', models.CharField(choices=[('lab01', 'Laboratorio 01'), ('lab02', 'Laboratorio 02'), ('lab03', 'Laboratorio 03'), ('lab04', 'Laboratorio 04'), ('lab05', 'Laboratorio 05'), ('lab06', 'Laboratorio 06'), ('lab07', 'Laboratorio 07'), ('lab08', 'Laboratorio 08')], default='lab01', max_length=5)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.teacher')),
            ],
            options={
                'ordering': ['course', 'group', 'laboratory', 'capacity', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.student')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.workload')),
            ],
            options={
                'ordering': ['workload', 'student', 'created'],
            },
        ),
        migrations.AddConstraint(
            model_name='workload',
            constraint=models.UniqueConstraint(fields=('course', 'group'), name='unique_workload'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('workload', 'student'), name='unique_inscription'),
        ),
    ]
