# Generated by Django 6.0.6 on 2026-06-25 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['curriculum', 'year', 'semester', 'code', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='acronym',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='laboratory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='laboratory_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='practice_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='enrollments.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(0, 'Sin semestre'), (1, 'I semestre'), (2, 'II semestre'), (3, 'III semestre'), (4, 'IV semestre'), (5, 'V semestre'), (6, 'VI semestre'), (7, 'VII semestre'), (8, 'VIII semestre'), (9, 'IX semestre'), (10, 'X semestre')], default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='theory_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(0, 'Sin año'), (1, '1er año'), (2, '2do año'), (3, '3er año'), (4, '4to año'), (5, '5to año'), (6, '6to año'), (7, '7mo año')], default=0),
        ),
    ]
